version: "3.8"

services:
  mysql:
    container_name: mysql # host name
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  # postgres:
  #   container_name: postgres # host name
  #   image: postgres:15.1
  #   restart: always
  #   environment: 
  #     POSTGRES_PASSWORD: example # postgres user: postgres
  #   ports:
  #     - 6543:5432
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
